version: "3.7"
services:
  jenkins:
    container_name: jenkins_controller
    build: jenkins/controller/
    user: jenkins
    ports:
      - 8080:8080
      - 50000:50000
    environment:
      DOCKER_HOST: "tcp://dind:2375"
    volumes:
      - /usr/bin/docker:/usr/bin/docker
    # Give access to the host netwoerk, in order to send Ansible command through SSH to the slaves
    network_mode: host

  dind:
    image: docker:dind
    user: root
    privileged: true
    container_name: dind
    expose:
      - 2375
    environment:
      DOCKER_TLS_CERTDIR: ""
    command: ["--insecure-registry=registry:5000"]

  registry:
    image: registry:2
    container_name: registry
    ports:
      - 5000:5000
