credentials:
  system:
    domainCredentials:
      - credentials:
          - usernamePassword:
              id: "vagrant_machine_credentials"
              password: "vagrant"
              scope: GLOBAL
              username: "vagrant"
jenkins:
  numExecutors: 10
  securityRealm:
    local:
      allowsSignup: false
      users:
        - id: admin
          password: admin
jobs:
  - script: |
      job('job_dsl') {
        description('Set up all jobs')
          
        scm {
          git {
            branches('*/main')
            remote {
              url('https://github.com/linoleparquet/portfolio-project.git')
            }
          }
        }
        steps {
          dsl {
            external('jenkins/dsl/job_dsl.groovy')
            removeAction('DELETE')
            ignoreExisting(ignore = false)
            removeViewAction('DELETE')
          }
        }
        triggers {
          cron('@midnight')
        }
      }
